In [1]:
import pandas as pd

In [2]:
MainDf=pd.read_csv('./DataFrames/MainDataFrame_raw.csv')
CleanDF=pd.read_csv('./DataFrames/MainDataFrameAfterCleaning.csv')

data before cleaning

In [3]:
MainDf.shape

(1344, 40)

In [5]:

MainDf.head()

,Unnamed: 0,Country,Year,Total inland transport infrastructure investment,Rail infrastructure maintenance,Road casualties (injured + killed),Road injury accident,Total inland passenger transport,Road passenger transport,Total inland freight transport in tonne-km per one thousand units of current USD GDP,...,Total Locomotives - Number at 31.12,Total pipelines operated - Length at 31.12 (km),Total transported - Tonnes (1000),Total goods - Tonnes (1 000),Total inland waterways - Length at 31.12 (km),Total railway enterprises - Number at 31.12,Total new mopeds - Number at 31.12 (Unit),Total self-propelled vessels - Number at 31.12 (Units),Total expenditures in road transport vehicles - Million national currency (current prices),Total expenditure in inland waterway vessels - Million national currency (current prices)
0,0,Albania,2000,110 421 157,3 838 572,620,428,5 424,(E) 5 299,630.5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,Armenia,2000,..,..,1 377,937,1 484,1 437,..,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,Australia,2000,4 111 727 074,NaN,28 591,NaN,268 358,256 806,694.4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,Austria,2000,1 674 000 000,508 000 000,55 905,42 126,NaN,NaN,221.8,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,Azerbaijan,2000,35 096 212,..,2 199,1 987,9 646,9 153,3 035.2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
MainDf.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1344 entries, 0 to 1343
Data columns (total 40 columns):
 #   Column                                                                                                Non-Null Count  Dtype
---  ------                                                                                                --------------  -----
 0   Unnamed: 0                                                                                            1344 non-null   int64
 1   Country                                                                                               1344 non-null   object
 2   Year                                                                                                  1344 non-null   int64
 3   Total inland transport infrastructure investment                                                      1029 non-null   object
 4   Rail infrastructure maintenance                                                                       882 non-null    object
 5   Road casualties (injured + killed)                                                                    1218 non-null   object
 6   Road injury accident                                                                                  1197 non-null   object
 7   Total inland passenger transport                                                                      840 non-null    object
 8   Road passenger transport                                                                              840 non-null    object
 9   Total inland freight transport in tonne-km per one thousand units of current USD GDP                  1071 non-null   object
 10  Road motor vehicles per one million units of current USD GDP                                          1050 non-null   object
 11  Road fatalities per one million inhabitant                                                            1092 non-null   object
 12  CO2 emissions from transport in tonnes per one million units of current USD GDP                       1040 non-null   object
 13  Total inland transport infrastructure capital value                                                   441 non-null    object
 14  Road traffic in vehicle-km per one thousand units of current USD GDP                                  840 non-null    object
 15  Density of road (km per one hundred sq. km)                                                           1029 non-null   object
 16  Share of household expenditure for purchase of vehicles in total household expenditure for transport  798 non-null    object
 17  Total passengers - Number (1 000)                                                                     396 non-null    object
 18  Total injury accidents - Number at 31.12 (Unit)                                                       405 non-null    object
 19  Total of train movements - Train-km [IV-07] (1 000)                                                   351 non-null    object
 20  Total Lines - Length operated at 31.12 (km)                                                           387 non-null    object
 21  Total Tracks - Length operated at 31.12 (km)                                                          360 non-null    object
 22  Total mopeds - Number at 31.12 (Unit)                                                                 306 non-null    object
 23  Total motorways - Length operated at 31.12 (km)                                                       387 non-null    object
 24  Killed                                                                                                396 non-null    object
 25  Total passengers - Passenger-km (millions)                                                            288 non-null    object
 26  Total oil pipeline transport - Tonnes (1 000)                                                         279 non-null    object
 27  Total vehicle movements - Vehicle-km (millions)                                                       243 non-null    object
 28  Total gas pipelines - length at 31.12 - km                                                            279 non-null    object
 29  Killed - rate per population                                                                          396 non-null    object
 30  Total Locomotives - Number at 31.12                                                                   342 non-null    object
 31  Total pipelines operated - Length at 31.12 (km)                                                       270 non-null    object
 32  Total transported - Tonnes (1000)                                                                     225 non-null    object
 33  Total goods - Tonnes (1 000)                                                                          234 non-null    object
 34  Total inland waterways - Length at 31.12 (km)                                                         207 non-null    object
 35  Total railway enterprises - Number at 31.12                                                           360 non-null    object
 36  Total new mopeds - Number at 31.12 (Unit)                                                             168 non-null    object
 37  Total self-propelled vessels - Number at 31.12 (Units)                                                216 non-null    object
 38  Total expenditures in road transport vehicles - Million national currency (current prices)            90 non-null     object
 39  Total expenditure in inland waterway vessels - Million national currency (current prices)             81 non-null     object
dtypes: int64(2), object(38)
memory usage: 420.1+ KB

clean data after cleaning

In [7]:
CleanDF.shape

(204, 35)

In [8]:
CleanDF.head()

,Unnamed: 0,Country,Year,Total inland transport infrastructure investment,Rail infrastructure maintenance,Total inland passenger transport,Road passenger transport,Total inland freight transport in tonne-km per one thousand units of current USD GDP,Road motor vehicles per one million units of current USD GDP,CO2 emissions from transport in tonnes per one million units of current USD GDP,...,Total inland waterways - Length at 31.12 (km),Total railway enterprises - Number at 31.12,Total self-propelled vessels - Number at 31.12 (Units),Road casualties (injured + killed),Road injury accident,Road fatalities per one million inhabitant,Total injury accidents - Number at 31.12 (Unit),Killed - rate per population,Killed,NaNs_at_this_row
0,0,Austria,2010,2.337000e+09,5.590000e+08,NaN,NaN,116.6,521.3,57.4,...,351.0,23.0,NaN,46410.0,35348.0,66.0,35348.0,6.6,552.0,7
1,1,Czech Republic,2010,2.340525e+09,6.698058e+08,80977.0,74386.0,324.5,423.4,79.4,...,676.0,24.0,46.0,25186.0,19676.0,76.6,19676.0,7.7,802.0,6
2,2,Finland,2010,1.280000e+09,6.670000e+08,76244.0,72285.0,161.0,536.4,50.0,...,8006.0,2.0,153.0,7945.0,6072.0,50.7,6072.0,5.1,272.0,4
3,3,France,2010,1.985350e+10,2.431000e+09,866108.0,763941.0,87.0,517.4,46.6,...,5110.0,36.0,890.0,88453.0,67288.0,61.4,67288.0,6.4,3992.0,7
4,4,Germany,2010,1.715700e+10,NaN,1046778.0,962892.0,146.8,510.4,43.6,...,7728.0,125.0,1336.0,374818.0,288297.0,44.6,288297.0,4.5,3648.0,8

In [10]:
CleanDF.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 204 entries, 0 to 203
Data columns (total 35 columns):
 #   Column                                                                                                Non-Null Count  Dtype
---  ------                                                                                                --------------  -----
 0   Unnamed: 0                                                                                            204 non-null    int64
 1   Country                                                                                               204 non-null    object
 2   Year                                                                                                  204 non-null    int64
 3   Total inland transport infrastructure investment                                                      183 non-null    float64
 4   Rail infrastructure maintenance                                                                       154 non-null    float64
 5   Total inland passenger transport                                                                      145 non-null    float64
 6   Road passenger transport                                                                              145 non-null    float64
 7   Total inland freight transport in tonne-km per one thousand units of current USD GDP                  180 non-null    float64
 8   Road motor vehicles per one million units of current USD GDP                                          198 non-null    float64
 9   CO2 emissions from transport in tonnes per one million units of current USD GDP                       184 non-null    float64
 10  Road traffic in vehicle-km per one thousand units of current USD GDP                                  175 non-null    float64
 11  Density of road (km per one hundred sq. km)                                                           183 non-null    float64
 12  Share of household expenditure for purchase of vehicles in total household expenditure for transport  191 non-null    float64
 13  Total passengers - Number (1 000)                                                                     149 non-null    float64
 14  Total of train movements - Train-km [IV-07] (1 000)                                                   153 non-null    float64
 15  Total Lines - Length operated at 31.12 (km)                                                           149 non-null    float64
 16  Total Tracks - Length operated at 31.12 (km)                                                          127 non-null    float64
 17  Total mopeds - Number at 31.12 (Unit)                                                                 124 non-null    float64
 18  Total motorways - Length operated at 31.12 (km)                                                       156 non-null    float64
 19  Total oil pipeline transport - Tonnes (1 000)                                                         101 non-null    float64
 20  Total vehicle movements - Vehicle-km (millions)                                                       137 non-null    float64
 21  Total gas pipelines - length at 31.12 - km                                                            92 non-null     float64
 22  Total Locomotives - Number at 31.12                                                                   113 non-null    float64
 23  Total pipelines operated - Length at 31.12 (km)                                                       104 non-null    float64
 24  Total goods - Tonnes (1 000)                                                                          110 non-null    float64
 25  Total inland waterways - Length at 31.12 (km)                                                         105 non-null    float64
 26  Total railway enterprises - Number at 31.12                                                           130 non-null    float64
 27  Total self-propelled vessels - Number at 31.12 (Units)                                                95 non-null     float64
 28  Road casualties (injured + killed)                                                                    192 non-null    float64
 29  Road injury accident                                                                                  198 non-null    float64
 30  Road fatalities per one million inhabitant                                                            202 non-null    float64
 31  Total injury accidents - Number at 31.12 (Unit)                                                       142 non-null    float64
 32  Killed - rate per population                                                                          204 non-null    float64
 33  Killed                                                                                                204 non-null    float64
 34  NaNs_at_this_row                                                                                      204 non-null    int64
dtypes: float64(31), int64(3), object(1)
memory usage: 55.9+ KB